### ISSUE TITLE
famebot makes it crash at startup

### ISSUE THREAD

**Issue by ouaklafoud** [natiiix/KRelay#11]
it crash simply loading Famebot

**Comment by natiiix** [comment]
Are you sure you are using a version of FameBot that references the correct `Lib_K_Relay.dll`? The old FameBot binary references an old (pre-X28.0.0) version of  `Lib_K_Relay.dll`, which does not support the Samurai class.

**Comment by ouaklafoud** [comment]
you are right this happen with the lastest version published on (post : mpgh OSFameBot release 5: Train AI).
since there is no upfate on the github since 8 months, i believe there is no famebot updated for samurai, and therefor nothing compatible with your newest version

**Comment by natiiix** [comment]
Oh, is that so? The K-Relay on MPGH should work if you use the latest XMLs. At least from what I've heard it should still work just fine, including the FameBot that's packed with it.

**Comment by ouaklafoud** [comment]
yes it does, but i wanted to test the famebot on your brand new sources :D 
 famebot code has evolve to be compatible with this one.
you can close this
